"use client";

import Image from "next/image";
import { useState } from "react";

type WeatherShot = {
  src: string;
  badge: string;
  title: string;
  caption: string;
  featured?: boolean;
};

const shots: WeatherShot[] = [
  {
    src: "weather-tracker-architecture-main1.webp",
    badge: "ARCHITECTURE",
    title: "End-to-end Azure architecture",
    caption:
      "GitHub Actions, Docker, ACR, Azure Container Apps, Application Insights, Azure Monitor, and Key Vault in the final delivery path.",
    featured: true,
  },
  {
    src: "weather-container-app-search.webp",
    badge: "CONTAINER APPS",
    title: "Live Azure Container Apps UI",
    caption: "Weather search running from the public HTTPS Container Apps endpoint.",
  },
  {
    src: "weather-github-actions-success.webp",
    badge: "CI / CD",
    title: "GitHub Actions pipeline success",
    caption: "Pipeline built the Docker image, pushed it to ACR, and updated Container Apps.",
  },
  {
    src: "weather-docker-desktop-container.webp",
    badge: "DOCKER",
    title: "Docker Desktop container",
    caption: "Local container validation before cloud deployment.",
  },
  {
    src: "weather-docker-desktop-images.webp",
    badge: "ACR / DOCKER",
    title: "Docker images and ACR tag",
    caption: "Local image and tagged ACR image prepared for publishing.",
  },
  {
    src: "weather-aci-running.webp",
    badge: "ACI",
    title: "Azure Container Instances validation",
    caption: "Short-lived ACI runtime proving the ACR image could execute in Azure.",
  },
  {
    src: "weather-local-container-home.webp",
    badge: "LOCAL",
    title: "Local container homepage",
    caption: "Weather Tracker running from the Dockerized FastAPI application.",
  },
  {
    src: "weather-fastapi-app-service-search.webp",
    badge: "APP SERVICE",
    title: "Earlier App Service deployment",
    caption: "Cloud-hosting validation before moving the final runtime to Container Apps.",
  },
  {
    src: "weather-appinsights-requests.webp",
    badge: "TELEMETRY",
    title: "Application Insights requests",
    caption: "Request telemetry generated by real application traffic.",
  },
  {
    src: "weather-appinsights-traces.webp",
    badge: "STRUCTURED LOGS",
    title: "Application Insights traces",
    caption: "Structured WeatherAPI request events searchable in Azure.",
  },
  {
    src: "weather-appinsights-error-traces.webp",
    badge: "ERROR SIGNAL",
    title: "Weather API error traces",
    caption: "KQL evidence used to validate the application-level failure signal.",
  },
  {
    src: "weather-monitor-alert-fired.webp",
    badge: "ALERT",
    title: "Azure Monitor alert fired",
    caption: "Scheduled query alert triggered when the Weather API error threshold was crossed.",
  },
  {
    src: "weather-alert-detail.webp",
    badge: "ALERT DETAIL",
    title: "Log search alert detail",
    caption: "Alert rule evidence showing the query, threshold, and fired condition.",
  },
  {
    src: "weather-alert-email.webp",
    badge: "ACTION GROUP",
    title: "Action Group email notification",
    caption: "Email notification proving that the alert action path completed successfully.",
  },
  {
    src: "weather-kql-syntax-error.webp",
    badge: "TROUBLESHOOTING",
    title: "KQL syntax issue",
    caption: "A real scheduled-query syntax problem encountered and corrected during alert creation.",
  },
  {
    src: "weather-appinsights-no-results.webp",
    badge: "TROUBLESHOOTING",
    title: "Initial no-results query",
    caption: "Early telemetry validation before instrumentation was corrected.",
  },
  {
    src: "weather-appinsights-success-requests.webp",
    badge: "REQUESTS",
    title: "Successful request table",
    caption: "Application Insights request data populated after telemetry started flowing.",
  },
  {
    src: "weather-appinsights-empty-traces.webp",
    badge: "TELEMETRY",
    title: "Empty traces stage",
    caption: "One of the early validation stages before application traces appeared correctly.",
  },
  {
    src: "weather-appinsights-overview.webp",
    badge: "OVERVIEW",
    title: "Application Insights overview",
    caption: "Application Insights resource view used during monitoring validation.",
  },
  {
    src: "weather-appinsights-metrics-overview.webp",
    badge: "METRICS",
    title: "Application Insights metrics",
    caption: "Azure metrics evidence from the monitoring stage.",
  },
  {
    src: "weather-unauthorized-api-error.webp",
    badge: "API ERROR",
    title: "Unauthorized WeatherAPI request",
    caption: "Early 401 issue later corrected through proper API-key and environment configuration.",
  },
];

export function WeatherGallery() {
  const [active, setActive] = useState<WeatherShot | null>(null);

  return (
    <>
      <div className="weather-gallery">
        {shots.map((shot) => (
          <button
            type="button"
            key={shot.src}
            className={`weather-shot ${shot.featured ? "weather-shot-featured" : ""}`}
            onClick={() => setActive(shot)}
          >
            <div className="weather-shot-image">
              <span>{shot.badge}</span>
              <Image
                src={`/images/${shot.src}`}
                alt={shot.title}
                fill
                sizes={
                  shot.featured
                    ? "(max-width: 700px) 100vw, (max-width: 1100px) 100vw, 50vw"
                    : "(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 25vw"
                }
              />
            </div>

            <div className="weather-shot-copy">
              <small>{shot.featured ? "PRIMARY SYSTEM EVIDENCE" : "BUILD EVIDENCE"}</small>
              <h3>{shot.title}</h3>
              <p>{shot.caption}</p>
            </div>
          </button>
        ))}
      </div>

      {active && (
        <div className="weather-modal" role="dialog" aria-modal="true">
          <button
            type="button"
            className="weather-modal-backdrop"
            aria-label="Close screenshot"
            onClick={() => setActive(null)}
          />

          <div className="weather-modal-panel">
            <div className="weather-modal-head">
              <div>
                <span>{active.badge}</span>
                <h3>{active.title}</h3>
              </div>
              <button type="button" onClick={() => setActive(null)}>
                CLOSE ×
              </button>
            </div>

            <div className="weather-modal-image">
              <Image
                src={`/images/${active.src}`}
                alt={active.title}
                width={1800}
                height={1100}
                sizes="94vw"
              />
            </div>

            <p>{active.caption}</p>
          </div>
        </div>
      )}
    </>
  );
}
